[FIX] Port-foward from 9.0
ingadhoc/account-financial-tools pull request #125
Opened 2018-09-05 20:27 UTC by zaoral

Related to:

[FIX] account_interests: Multiple fixes for this module (#124)

To be able to updagre this module with all the new changes in the PR.

2018-09-05 23:57 UTC, jjscarafia requested changes
Una pregunta y una pavada..

2018-09-05 23:57 UTC, jjscarafia commented on account_interests/models/res_company_interest.py
> +            invoice.write({'invoice_line_ids': [
Hace falta el invoice write si ya se le está pasando el "invoice" a la línea? Digo, la línea solita ya debería crearse en la factura si tiene el campo "invoice_id", no?

2018-09-05 23:57 UTC, jjscarafia commented on account_interests/models/res_company_interest.py
> +        domain=[('active', '=', True)]
Este dominio no haría falta

2018-09-06 12:51 UTC, zaoral commented on account_interests/models/res_company_interest.py
> +            invoice.write({'invoice_line_ids': [
si. exactamente. prefieres que haga un invoice_line.create()? 

NOTA: Lo bueno de la manera actual es que si en un futuro necesitamos crear mas lineas en la factura por recargo de mora este invoice.write() seria la manera menos costosa de hacer la escritura porque seria uno por todas las lineas, no uno por cada linea.

2018-09-06 13:54 UTC, jjscarafia approved these changes

2018-09-06 13:54 UTC, merged