[ADD] account_ux: do not let the user create rates without company if already had rates with company before the new rate date
ingadhoc/account-financial-tools pull request #128
Opened 2018-09-11 18:17 UTC by zaoral

This is required since create new records without company will make then
invisible, odoo will search for the ones with the last date with company
set. If a user create a rate without company this one will never be take into
account. Adding the constraint we avoid this human error.

2018-09-11 21:41 UTC, jjscarafia requested changes
Excelente kathy, dejo un comentario por una pavada..

2018-09-11 21:41 UTC, jjscarafia commented on account_ux/models/res_currency_rate.py
> +                ('currency_id', '<=', rec.currency_id.id),
Acá imagino que sería = en vez de <=, no?

2018-09-12 12:31 UTC, zaoral commented on account_ux/models/res_currency_rate.py
> +                ('currency_id', '<=', rec.currency_id.id),
@jjscarafia  puse >= porque en el caso particular de las res.currency.rate el campo name es de tipo fecha. nos interesa son los rates que sean en fecha previa o igual a la fecha del nuevo rate.

2018-09-12 21:39 UTC, jjscarafia commented on account_ux/models/res_currency_rate.py
> +                ('currency_id', '<=', rec.currency_id.id),
perfecto, eso lo vi, pero el <= está tmb en el currency "'currency_id', '<=', rec.currency_id.id"
Me refería a ese pero no quedó claro...

2018-09-13 12:36 UTC, zaoral commented on account_ux/models/res_currency_rate.py
> +                ('currency_id', '<=', rec.currency_id.id),
Tienes razon Juan, no lo habia visto. voy a corregirlo

2018-09-13 13:15 UTC, zaoral commented on account_ux/models/res_currency_rate.py
> +                ('currency_id', '<=', rec.currency_id.id),
Listo el cambio y el push

2018-09-13 18:18 UTC, jjscarafia approved these changes

2018-09-13 18:18 UTC, merged