[MIG] account_interests: Migration to 13.0
ingadhoc/account-financial-tools pull request #220
Opened 2020-02-11 21:44 UTC by daniellibonati

* Adapted code to v13
* Removed field invoice_receivable_account_id, use partner default instead

2020-02-18 21:03 UTC, jjscarafia requested changes

2020-02-18 21:03 UTC, jjscarafia commented on account_interests/models/res_company_interest.py
> +        line = self.env['account.move.line'].new(dict(
cambiaría la forma de llamar "dict(" no es muy odoo way, directamente definir el diccionario con {}

2020-02-18 21:03 UTC, jjscarafia commented on account_interests/models/res_company_interest.py
> -            force_company=company.id).new(dict(
este force company supongo que sigue siendo necesario o robaría de como se preparan vals en otros casos de uso. Sobre todo probaría que funcione bien si admin / odoobot están logueados en una cia pero que la cia par ala cual se crean los intereses es de otra, hay que ver que las cuentas contables y demás datos se computen bien

2020-03-04 20:50 UTC, daniellibonati commented on account_interests/models/res_company_interest.py
> -            force_company=company.id).new(dict(
Ok, lo reformulé sin force

2020-03-10 16:48 UTC, merged