[IMP]account_ux: improve change currency message
ingadhoc/account-financial-tools pull request #340
Opened 2022-05-17 16:32 UTC by pablohmontenegro

Ticket: 51807
Improve change currency message and set rate when both currency and values are changed simultaneously

2022-05-17 16:33 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/340).

2022-05-17 18:39 UTC, zaoral requested changes
@pablohmontenegro 
Buenas de nuevo Pablito.
Gracias por el PR

Te dejo aca un par de comentarios de puntos a mewjorar y algunas dudas que me quearon si quieres la vemos por videollamda mas rapido.

Saludos!

2022-05-17 18:39 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> +        message = _("Currency changed from %s to %s with rate %s") % (
moveria la variable mesage y el message_post al final del metodo donde estaba antes, al menos qu ehay aalguna razon de porque hacelro aca?

2022-05-17 18:39 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> +                self.move_id.l10n_ar_currency_rate = '0.0'
```suggestion
                self.move_id.l10n_ar_currency_rate = 0.0
```
en este caso el valor seria el valor del numero flotanto, no seria necesario pasarlo en una cadena '0.0'

2022-05-17 18:39 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> +            self.move_id.l10n_ar_currency_rate = self.currency_rate
El campo l10n_ar_currency_rate no es alcanzado en el modulo account_ux (ese campo es definido en el modulo l10n_ar y account_ux no hereda ni debe heredar de l10n_ar.)

En este caso haria algo similiar a lo siguiente: si el modulo esta instalaod entonces intento escribir el campo, de lo contrario no lo ho hacemos porque si solo esta instalado account_ux, o account_ux con otra localizacion dara error :(

Esto seria para cada vez que vayas a consultar o escribir el campo l10n_ar_currency_rate
```suggestion
            if self.env['ir.module.module'].search([('name', '=', 'l10n_ar')], limit=1).state in ('installed', 'to install', 'to upgrade'):
                self.move_id.l10n_ar_currency_rate = self.currency_rate
```

2022-05-17 18:39 UTC, zaoral commented on account_ux/__manifest__.py
> +    'version': "15.0.1.4.0",
en este caso no hicimos cambios en en base de datos (vistas, campos, etc) asi que no seria necesario hacer el +1 de version

2022-05-17 18:39 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> -    @api.onchange('currency_to_id')
Aca me queda la duda de porque eliminamos este onchange.
te dejo video https://drive.google.com/file/d/1je8dntxK2X0ce10d1s1Me5Ulc_b0_6mJ/view

2022-06-03 13:54 UTC, zaoral requested changes

2022-06-03 13:54 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> +                self.move_id.l10n_ar_currency_rate = self.currency_rate
esti debemos quitarlo porque no deberia afectar a la tasa de la moneda en la factura

2022-06-03 13:54 UTC, zaoral commented on account_ux/wizards/account_change_currency.py
> +                message = _("Currency changed from %s to %s with rate %s. Currency rate forced") % (
ver de cambiar el mensaje para que no diga currency rate. sino ratio de conversion

2022-06-15 16:45 UTC, pablohmontenegro commented
This PR is not goint to be implemented because of a misunderstood.

2022-06-15 16:45 UTC, closed without merging