[FIX] account_debt_report: invoice detail on debt report
ingadhoc/account-financial-tools pull request #360
Opened 2022-09-26 15:25 UTC by mem-adhoc

Ticket: 55619

2022-09-26 15:25 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/360).

2022-09-27 14:35 UTC, zaoral requested changes
Hi @mem-adhoc 
Thank you for the PR.
I have added some suggested changes.
Please review and let me know.

Best Regards

2022-09-27 14:35 UTC, zaoral commented on account_debt_report/models/res_partner.py
> +                    inv_line_name = inv_line.name
```suggestion
                    inv_line_name = inv_line.name or "Sin descripción"
```

2022-09-27 14:35 UTC, zaoral commented on account_debt_report/models/res_partner.py
> +                    inv_line_product_uom_id_name = inv_line.product_uom_id.name
```suggestion
                    inv_line_product_uom_id_name = inv_line.product_uom_id.name or "Sin unidad de medida"
```

2022-09-27 14:35 UTC, zaoral commented on account_debt_report/models/res_partner.py
> +                        inv_line_product_uom_id_name = "Sin unidad de medida"
```suggestion
```

2022-09-28 15:23 UTC, zaoral approved these changes

2022-09-28 15:23 UTC, zaoral commented
@roboadhoc r+

2022-09-28 15:26 UTC, closed without merging