[WIP] account_payment_term_surcharge
ingadhoc/account-financial-tools pull request #381
Opened 2023-01-11 22:21 UTC by ica-adhoc

2023-01-11 22:21 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-financial-tools/pull/381).

2023-01-12 10:52 UTC, jjscarafia requested changes

2023-01-12 10:52 UTC, jjscarafia commented on account_payment_term_surcharge/__manifest__.py
> +    'summary': 'Calculate and generate term surcharge for payments',
Al name le pondría: Surcharges on payment terms
En summary: Allow to add surcharges for invoices on payment terms
(o algo así)

2023-01-12 10:52 UTC, jjscarafia commented on account_payment_term_surcharge/models/account_move.py
> +
faltaría un enter acá, es una pavada jeje, pero es algo de estilos que en teoría el vs code debería mostrar (si está bien configurado)

2023-01-12 10:52 UTC, jjscarafia commented on account_payment_term_surcharge/models/account_payment_term_surcharge.py
> +    payment_id = fields.Many2one('account.payment.term', string='Payment Terms', required=True, index=True, ondelete='cascade')
a esta campo lo lamaría "payment_term_id" o similar. Porque payment_id me hace pensar en un inculo a un pago. 
es verdad que veo que odoo lo llama así jeje, horrible
agregate de ultima un comentario arriba diciendo lo llamamos "payment_id" porque odoo lo llama así en las "account.payment.term.line" aunque no nos parece lo más lindo

2023-01-12 10:52 UTC, jjscarafia commented on account_payment_term_surcharge/models/account_move.py
> +            for surcharge in surcharges:
no revisé en profundidad, pero sospecho que algo de esto se puede llegar a mejorar. Me llama la atención tener que usar los [0] y [1] por ahí pegale un vistazo a este código con kathy

2023-03-07 19:48 UTC, zaoral commented
@roboadhoc r+

2023-03-07 19:52 UTC, zaoral commented
@roboadhoc retry

2023-03-07 20:08 UTC, nicomacr commented
@roboadhoc r+

2023-03-07 20:28 UTC, closed without merging

2023-03-07 20:29 UTC, zaoral commented
superseded by https://github.com/ingadhoc/account-financial-tools/pull/388 thanks to problems with old runbot