[FIX] account_interests: not able to create debit note
ingadhoc/account-financial-tools pull request #382
Opened 2023-01-19 04:44 UTC by zaoral

Crear la nota de debito en el diario de ventas compatible y sugerido por defecto en Odoo.

Antes de este cambio si teniamos por ejemplo si necesitamos generar una nota de debito de exportación daba error porque en si siempre elegiamos un tipo de diario regular de ventas que no era compatible

2023-01-19 15:05 UTC, ica-adhoc requested changes
@zaoral it would be necessary to make a small change, the rest seems to be all ok

2023-01-19 15:05 UTC, ica-adhoc commented on account_interests/models/res_company_interest.py
> +                {'res_partner': partner_id, 'move_type': 'out_invoice'}).journal_id
'res_partner' does not exist in the 'account.move' model, it should be changed to partner_id

2023-04-27 18:51 UTC, ica-adhoc commented
@roboadhoc r+

2023-04-27 20:04 UTC, closed without merging

2023-04-27 20:07 UTC, zaoral commented
Superseded by https://github.com/ingadhoc/account-financial-tools/pull/407