[FIX] account_ux: fecha de vencimiento en facturas
ingadhoc/account-financial-tools pull request #421
Opened 2023-06-29 19:51 UTC by pablohmontenegro

Ticket: 63079
Si la factura no tiene término de pago y la misma tiene fecha de vencimiento anterior al día de hoy y la factura no tiene fecha entonces cuando se publica la factura, la fecha de vencimiento tiene que coincidir con la fecha de hoy.

2023-06-29 19:52 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/421).

2023-07-07 16:22 UTC, ica-adhoc requested changes

2023-07-07 16:22 UTC, ica-adhoc commented on account_ux/models/account_move.py
> +        else:
@pablohmontenegro esta sobrando este else? o esta mal identado?

2023-07-08 01:11 UTC, ica-adhoc approved these changes

2023-07-08 01:11 UTC, ica-adhoc commented
@roboadhoc r+

2023-07-08 01:13 UTC, roboadhoc commented
@pablohmontenegro @ica-adhoc unable to stage: merge conflict

2023-07-08 01:17 UTC, ica-adhoc approved these changes

2023-07-08 01:17 UTC, ica-adhoc commented
@roboadhoc r+

2023-07-08 01:29 UTC, closed without merging