[FIX] account_ux: delete draft vendor bill
ingadhoc/account-financial-tools pull request #429
Opened 2023-07-17 12:00 UTC by pablohmontenegro

Ticket: 55058
This pr replaces https://github.com/odoo/odoo/pull/100728 Description of the issue/feature this PR addresses:

On Runbot Odoo enterprise v15.0 install l10n_ar_edi module (Argentina Electronic Invoicing).

Select and work on "(AR) Responsable Inscripto" Company.

Go to Accounting > Vendor > Bills.

Create a Vendor bill with vendor "ADHOC SA", document number 1-5 (this is an example), and save.

Try to delete de bill, a see the sequence problem. "User Error: You cannot delete this entry, as it has already consumed a sequence number and is not the last one in the chain. You should probably revert it instead."

Current behavior before PR:
Can't delete draft vendor bill situated in a company from l10n_ar localization.

Desired behavior after PR is merged:
Is possible to delete draft vendor bills situated in a company from l10n_ar localization.

2023-07-17 12:01 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/429).

2023-11-10 17:13 UTC, pablohmontenegro commented
This pull request is replaced by https://github.com/ingadhoc/odoo-argentina/pull/749

2023-11-15 14:39 UTC, zaoral requested changes

2023-11-15 14:39 UTC, zaoral commented on account_ux/models/account_move.py
> +        """Delete vendor bills without verifying if they are the last ones of the sequence chain."""
```suggestion
        """Delete vendor bills without verifying if they are the last ones of the sequence chain."""
        # Field l10n_latam_use_documents is defined in module l10n_latam_invoice_document but l10n_ax_ux doesn´t has it as depends.
        l10n_latam_invoice_document_installed = self.env['ir.module.module'].search([
            ('name', '=', 'l10n_latam_invoice_document'),
            ('state', '=', 'installed'),
        ])
        if l10n_latam_invoice_document_installed:
        ```

2023-11-16 13:34 UTC, zaoral requested changes

2023-11-16 13:34 UTC, zaoral commented on account_ux/models/account_move.py
> +            return super(AccountMove, self - vendor)._unlink_forbid_parts_of_chain()
opcion 1
```suggestion
       vendor = self.filtered(lambda x: x._is_manual_document_number() and x.l10n_latam_use_documents) if l10n_latam_invoice_document_installed else self.env['account.move'] 
       return super(AccountMove, self - vendor)._unlink_forbid_parts_of_chain()
```

2023-11-16 13:34 UTC, zaoral commented on account_ux/models/account_move.py
> +            return super(AccountMove, self - vendor)._unlink_forbid_parts_of_chain()
opcion 2

```suggestion
        if l10n_latam_invoice_document_installed:
            vendor = self.filtered(lambda x: x._is_manual_document_number() and x.l10n_latam_use_documents)
            return super(AccountMove, self - vendor)._unlink_forbid_parts_of_chain()
        else:
            return super()._unlink_forbid_parts_of_chain()
```

2023-11-16 20:09 UTC, zaoral commented
@roboadhoc r+

2023-11-16 20:13 UTC, closed without merging