[IMP] account_ux: check date and invoice date in sale documents
ingadhoc/account-financial-tools pull request #461
Opened 2023-11-08 17:42 UTC by pablohmontenegro

Task: 34851
Prevenir que en facturas de cliente queden distintos los campos de factura/recibo y fecha (date e invoice date). Pueden quedar distintos si se modifica alguna de esas fechas a través de edición masiva por ejemplo, entonces con esta constrains queremos prevenir que eso suceda.

2023-11-08 17:43 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-financial-tools/pull/461).

2023-11-08 18:45 UTC, maq-adhoc approved these changes

2023-11-14 19:17 UTC, zaoral requested changes

2023-11-14 19:17 UTC, zaoral commented on account_ux/models/account_move.py
> +                error_msg += rec.name + '                ' + str(rec.date) + '                ' + str(rec.invoice_date) + '\n'
```suggestion
                error_msg += rec.display_name + '                ' + str(rec.date) + '                ' + str(rec.invoice_date) + '\n'
```

2023-11-14 19:17 UTC, zaoral commented on account_ux/models/account_move.py
> +        invoices_to_check = self.filtered(lambda x: (x.move_type in ('out_invoice', 'out_refund', 'out_receipt') and x.date!=x.invoice_date) if (x.move_type in ('out_invoice', 'out_refund', 'out_rece
```suggestion
        invoices_to_check = self.filtered(lambda x:  x.date != x.invoice_date if (x.is_sale_document() and x.invoice_date and x.date) else False)
```

2023-11-14 19:17 UTC, zaoral commented on account_ux/models/account_move.py
> +            error_msg="\nInvoice                                              Date                            Invoice Date\n"
```suggestion
            error_msg = _("\nDate\tInvoice Date\tInvoice\n")
```

2023-11-17 13:47 UTC, zaoral requested changes

2023-11-17 13:47 UTC, zaoral commented on account_ux/i18n/es.po
> +#. module: account_ux
remove translations, leave copy to send to PO so they can do the translation from transifex

2023-11-22 19:32 UTC, zaoral commented on account_ux/models/account_move.py
> +            error_msg = _('\nDate\t\t\tInvoice Date\t\tInvoice\n')
```suggestion
            error_msg = '\n%s\t\t\t%s\t\t%s\n' % (_('Date'), _('Invoice Date'),  _('Invoice'))
```

2023-11-22 19:35 UTC, zaoral commented
@roboadhoc override=ci/runbot-oba
@roboadhoc r+

2023-11-22 19:41 UTC, closed without merging